export const ADD_USER="ADD_USER";
export const DELETE_USER="DELETE_USER";
export const GET_ALL_USER="GET_ALL_USER";

export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";
export const ADD_USER_ERROR="ADD_USER_ERROR";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR="DELETE_USER_ERROR";
export const GET_ALL_USER_SUCCESS="GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_ERROR="GET_ALL_USER_ERROR";